### ISSUE TITLE
縦書きグローバルメニュー

### ISSUE THREAD

**Issue by inc2734** [inc2734/snow-monkey#661]
### 参考
- http://www.gallerymitsumi.jp/

**Comment by inc2734** [comment]
とりあえず初稿

```css
[data-has-global-nav] .p-global-nav {
    display: flex;
    justify-content: center; /* center のとき */
    /* justify-content: start; 1row のとき */
    /* justify-content: flex-end; 2row のとき */
}

[data-has-global-nav] .p-global-nav .c-navbar {
    display: inline-flex;
}

[data-has-global-nav] .p-global-nav .c-navbar__item > a {
    writing-mode: vertical-rl;
    align-items: flex-start;
    /* @include _padding(0, 1, 1); 1row のとき*/
    padding: 1.40217rem;
    /* @include _padding(1); 2row, center のとき */
}
```
